version: 1.6.0+{build}

clone_folder: c:\project\stumpless

configuration:
- Release
- Debug

image:
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015

platform:
- x64

environment:
  matrix:
  - arch: Win64
    cpp_enabled: OFF
  - arch: Win64
    cpp_enabled: ON

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )

install:
 - set PATH=C:\Ruby26-x64\bin;%PATH%
 - if %cpp_enabled%=="ON" ( bundle install )

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake .. -G %generator% -DCMAKE_BUILD_TYPE=%configuration% -DENABLE_CPP=%cpp_enabled%

build:
  project: c:\project\stumpless\build\stumpless.vcxproj

test_script:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - msbuild c:\project\stumpless\build\check.vcxproj
  - if %cpp_enabled%=="ON" ( msbuild c:\project\stumpless\build\check-cpp.vcxproj )
  - msbuild c:\project\stumpless\build\examples.vcxproj
