name: "Cygwin"

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  cygwin:
    name: "cygwin, release"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Cache Google Test and Benchmark
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        id: cache-google-libs
        with:
          path: |
            C:/gtest
            C:/benchmark
          key: ${{ runner.os }}-${{ hashFiles('**/gtest.cmake', '**/benchmark.cmake') }}
      - name: Install Cygwin Base
        run: |
          choco install --no-progress cygwin
      - name: Install Cygwin Packages
        run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P gcc-core,gcc-g++,make,cmake
        shell: cmd
      - name: Configure
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "cmake -DCMAKE_BUILD_TYPE=Release -DGTEST_PATH=/cygdrive/c/gtest -DBENCHMARK_PATH=/cygdrive/c/benchmark -DCMAKE_INSTALL_PREFIX=/usr ."
        shell: cmd
      - name: Build Google Test and Benchmark
        if: steps.cache-google-libs.outputs.cache-hit != 'true'
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "mkdir /cygdrive/c/gtest"
          bash.exe -c "mkdir /cygdrive/c/benchmark"
          bash.exe -c "make gtest benchmark export-gtest export-benchmark"
        shell: cmd
      - name: Build
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make all"
        shell: cmd
      - name: Test
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make check"
        shell: cmd
      - name: Run Benchmarks
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make bench"
        shell: cmd
      - name: Run Examples
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make examples"
        shell: cmd
      - name: Install
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make install"
        shell: cmd
      - name: Test Build with Install
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "gcc docs/examples/basic/basic_example.c -lstumpless -o run_example.exe && ./run_example.exe"
        shell: cmd
