name: "Windows"

on:
  push:
  pull_request:
    branches:
      - latest

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  windows-debug:
    name: "windows, debug"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug .
      - name: Build
        run: |
          cmake --build . --config Debug
      - name: Test
        run: |
          cmake --build . --config Debug --target check
      - name: Thread Safety Tests
        run: |
          cmake --build . --config Debug --target check-thread-safety
      - name: Run Examples
        run: |
          cmake --build . --config Debug --target examples
  windows-release:
    name: "windows, release"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check
      - name: Thread Safety Tests
        run: |
          cmake --build . --config Release --target check-thread-safety
      - name: Run Examples
        run: |
          cmake --build . --config Release --target examples
  windows-release-static:
    name: "windows, release, static library"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check
      - name: Thread Safety Tests
        run: |
          cmake --build . --config Release --target check-thread-safety
      - name: Run Examples
        run: |
          cmake --build . --config Release --target examples
  windows-release-single-file:
    name: "windows, release, single file library"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check-single-file
      - name: Run Examples
        run: |
          cmake --build . --config Release --target examples-single-file
  windows-sqlite3:
    name: "windows, release, sqlite3 source"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Download SQLite3 Amalgamation
        run: |
          Invoke-WebRequest -Uri https://sqlite.org/2023/sqlite-amalgamation-3440200.zip -OutFile sqlite.zip
          Expand-Archive -Path sqlite.zip
        shell: pwsh
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DSQLITE3_SRC_PATH=D:\a\stumpless\stumpless\sqlite\sqlite-amalgamation-3440200\sqlite3.c -DSQLITE3_INCLUDE_PATH=D:\a\stumpless\stumpless\sqlite\sqlite-amalgamation-3440200\sqlite3.h .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check
      - name: Thread Safety Tests
        run: |
          cmake --build . --config Release --target check-thread-safety
  windows-all-disabled:
    name: "windows, all features disabled"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DENABLE_CHAIN_TARGETS=OFF -DENABLE_JOURNALD_TARGETS=OFF -DENABLE_NETWORK_TARGETS=OFF -DENABLE_SOCKET_TARGETS=OFF -DENABLE_SQLITE3_TARGETS=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_THREAD_SAFETY=OFF .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check
      - name: Run Examples
        run: |
          cmake --build . --config Release --target examples
  windows-cpp:
    name: "windows, with c++"
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: ruby/setup-ruby@70da3bbf44ac06db1b0547ce2acc9380a5270d1e # v1.175.0
        with:
          ruby-version: '3.2'
      - name: Install Gems
        run: |
          gem install wrapture
      - name: Configure
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DENABLE_CPP=ON .
      - name: Build
        run: |
          cmake --build . --config Release
      - name: Test
        run: |
          cmake --build . --config Release --target check-cpp
      - name: Run Example
        run: |
          cmake --build . --config Release --target run-example-cpp
